package utilities;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;

public class Res_listes {
	public static ObservableList<String> pays_groupe = FXCollections.observableArrayList("Afghanistan",
			"Afrique du Sud", "Akrotiri", "Albanie", "Algérie", "Allemagne", "Andorre", "Angola", "Anguilla",
			"Antarctique", "Antigua-et-Barbuda", "Antilles néerlandaises", "Arabie saoudite", "Arctic Ocean",
			"Argentine", "Arménie", "Aruba", "Ashmore and Cartier Islands", "Atlantic Ocean", "Australie", "Autriche",
			"Azerbaïdjan", "Bahamas", "Bahreïn", "Bangladesh", "Barbade", "Belau", "Belgique", "Belize", "Bénin",
			"Bermudes", "Bhoutan", "Biélorussie", "Birmanie", "Bolivie", "Bosnie-Herzégovine", "Botswana", "Brésil",
			"Brunei", "Bulgarie", "Burkina Faso", "Burundi", "Cambodge", "Cameroun", "Canada", "Cap-Vert", "Chili",
			"Chine", "Chypre", "Clipperton Island", "Colombie", "Comores", "Congo", "Coral Sea Islands",
			"Corée du Nord", "Corée du Sud", "Costa Rica", "Côte d'Ivoire", "Croatie", "Cuba", "Danemark", "Dhekelia",
			"Djibouti", "Dominique", "Égypte", "Émirats arabes unis", "Équateur", "Érythrée", "Espagne", "Estonie",
			"États-Unis", "Éthiopie", "ex-République yougoslave de Macédoine", "Finlande", "France", "Gabon", "Gambie",
			"Gaza Strip", "Géorgie", "Ghana", "Gibraltar", "Grèce", "Grenade", "Groenland", "Guam", "Guatemala",
			"Guernsey", "Guinée", "Guinée équatoriale", "Guinée-Bissao", "Guyana", "Haïti", "Honduras", "Hong Kong",
			"Hongrie", "Ile Bouvet", "Ile Christmas", "Ile Norfolk", "Iles Cayman", "Iles Cook",
			"Iles des Cocos (Keeling)", "Iles Falkland", "Iles Féroé", "Iles Fidji",
			"Iles Géorgie du Sud et Sandwich du Sud", "Iles Heard et McDonald", "Iles Marshall", "Iles Pitcairn",
			"Iles Salomon", "Iles Svalbard et Jan Mayen", "Iles Turks-et-Caicos", "Iles Vierges américaines",
			"Iles Vierges britanniques", "Inde", "Indian Ocean", "Indonésie", "Iran", "Iraq", "Irlande", "Islande",
			"Israël", "Italie", "Jamaïque", "Jan Mayen", "Japon", "Jersey", "Jordanie", "Kazakhstan", "Kenya",
			"Kirghizistan", "Kiribati", "Koweït", "Laos", "Lesotho", "Lettonie", "Liban", "Liberia", "Libye",
			"Liechtenstein", "Lituanie", "Luxembourg", "Macao", "Madagascar", "Malaisie", "Malawi", "Maldives", "Mali",
			"Malte", "Man, Isle of", "Mariannes du Nord", "Maroc", "Maurice", "Mauritanie", "Mayotte", "Mexique",
			"Micronésie", "Moldavie", "Monaco", "Monde", "Mongolie", "Monténégro", "Montserrat", "Mozambique",
			"Namibie", "Nauru", "Navassa Island", "Népal", "Nicaragua", "Niger", "Nigeria", "Nioué", "Norvège",
			"Nouvelle-Calédonie", "Nouvelle-Zélande", "Oman", "Ouganda", "Ouzbékistan", "Pacific Ocean", "Pakistan",
			"Panama", "Papouasie-Nouvelle-Guinée", "Paracel Islands", "Paraguay", "Pays-Bas", "Pérou", "Philippines",
			"Pologne", "Polynésie française", "Porto Rico", "Portugal", "Qatar", "République centrafricaine",
			"République démocratique du Congo", "République dominicaine", "République tchèque", "Roumanie",
			"Royaume-Uni", "Russie", "Rwanda", "Sahara occidental", "Saint-Christophe-et-Niévès", "Sainte-Hélène",
			"Sainte-Lucie", "Saint-Marin", "Saint-Pierre-et-Miquelon", "Saint-Siège", "Saint-Vincent-et-les-Grenadines",
			"Salvador", "Samoa", "Samoa américaines", "Sao Tomé-et-Principe", "Sénégal", "Serbie", "Seychelles",
			"Sierra Leone", "Singapour", "Slovaquie", "Slovénie", "Somalie", "Soudan", "Southern Ocean",
			"Spratly Islands", "Sri Lanka", "Suède", "Suisse", "Suriname", "Swaziland", "Syrie", "Tadjikistan",
			"Taïwan", "Tanzanie", "Tchad", "Terres australes françaises", "Territoire britannique de l'Océan Indien",
			"Thaïlande", "Timor Oriental", "Togo", "Tokélaou", "Tonga", "Trinité-et-Tobago", "Tunisie", "Turkménistan",
			"Turquie", "Tuvalu", "Ukraine", "Union européenne", "Uruguay", "Vanuatu", "Venezuela", "Viêt Nam",
			"Wake Island", "Wallis-et-Futuna", "West Bank", "Yémen", "Zambie", "Zimbabwe");

	public static ObservableList<String> instru_membre = FXCollections.observableArrayList("Pas d'instrument", "Accord",
			"Accordeon", "Accordeons", "Accordeur", "Accordeurs", "Accords", "Acetabule", "Acetabules", "Acetabulum",
			"Acetabulums", "Affut", "Affuts", "Agada", "Agadas", "Aile", "Ailes", "Alligator", "Alligators", "Alto",
			"Altos", "Amati", "Amatis", "Angelique", "Angeliques", "Apollon", "Apollons", "Appeau", "Appeaux",
			"Archiluth", "Archiluths", "Arcon", "Arcons", "Argol", "Argols", "Ars", "Asa", "Aubois", "Aulique",
			"Auliques", "Aura", "Auras", "Automate", "Automates", "Bachas", "Bagne", "Bagnes", "Balafon", "Balafons",
			"Balalaika", "Balalaikas", "Balan", "Bamboula", "Bamboulas", "Bandoneon", "Bandoneons", "Banjo", "Banjos",
			"Bar", "Barbat", "Bars", "Baryton", "Barytons", "Basse", "Basses", "Basset", "Bassets", "Bassin",
			"Bassinet", "Bassinets", "Bassins", "Basson", "Bassons", "Bat", "Bata", "Batas", "Batelet", "Batelets",
			"Baton", "Batons", "Bats", "Batterie", "Batteries", "Baya", "Bayas", "Bebe", "Bebes", "Bec", "Becs",
			"Bedon", "Bedons", "Beffroi", "Beffrois", "Bele", "Beles", "Beliere", "Belieres", "Bendir", "Bendirs",
			"Berimbau", "Berimbaus", "Bidon", "Bidons", "Bigophone", "Bigophones", "Bina", "Binas", "Bine", "Bines",
			"Biniou", "Binious", "Biwa", "Biwas", "Bob", "Bobine", "Bobines", "Bobs", "Bock", "Bocks", "Bodega",
			"Bodegas", "Bomba", "Bombarde", "Bombardes", "Bombardon", "Bombardons", "Bombas", "Bombyx", "Bondions",
			"Bongo", "Bongos", "Boomerang", "Boomerangs", "Bordons", "Boula", "Boulas", "Bouquin", "Bouquins",
			"Bourdon", "Bourdons", "Bouzouki", "Bouzoukis", "Braillard", "Braillards", "Branleur", "Branleurs",
			"Brimbale", "Brimbales", "Bruant", "Bruants", "Buccin", "Buccins", "Buche", "Buches", "Bugle", "Bugles",
			"Bun", "Buns", "Buse", "Buses", "Buzuki", "Buzukis", "Cabosse", "Cabosses", "Cabrette", "Cabrettes",
			"Caille", "Cailler", "Cailles", "Caisse", "Caisses", "Calamina", "Calaminas", "Calamus", "Calebasse",
			"Calebasses", "Campane", "Campanelle", "Campanelles", "Campanes", "Canon", "Canons", "Car", "Caramel",
			"Caramels", "Carillon", "Carillons", "Carra", "Carras", "Carrelet", "Carrelets", "Carron", "Carrons",
			"Cars", "Cascades", "Casque", "Casques", "Castagnettes", "Cava", "Cavas", "Celesta", "Celestas", "Cerceau",
			"Cerceaux", "Cervelas", "Chalumeau", "Chalumeaux", "Chanterelle", "Chanterelles", "Chanteur", "Chanteurs",
			"Chapee", "Chapees", "Char", "Charango", "Charangos", "Charleston", "Charlestons", "Chars", "Chat", "Chats",
			"Chenille", "Chenilles", "Chevre", "Chevres", "Chevrete", "Chevrette", "Chevrettes", "Chili", "Chilis",
			"China", "Chinas", "Chinoise", "Chinoises", "Chofar", "Chofars", "Choriste", "Choristes", "Choron",
			"Chorons", "Chorus", "Chouette", "Chouettes", "Chronometre", "Chronometres", "Cigale", "Cigales", "Cistre",
			"Cistres", "Citera", "Citeras", "Cithare", "Cithares", "Clabot", "Clabots", "Claire", "Claires", "Clairon",
			"Clairons", "Clapet", "Clapets", "Claquette", "Claquettes", "Claquoir", "Claquoirs", "Clarain", "Clarains",
			"Clarine", "Clarines", "Clarinette", "Clarinettes", "Classique", "Classiques", "Clave", "Clavecin",
			"Clavecins", "Claves", "Clavicorde", "Clavicordes", "Clavier", "Claviers", "Clepsydre", "Clepsydres",
			"Cliquet", "Cliquets", "Cliquette", "Cliquettes", "Cloche", "Cloches", "Clochette", "Clochettes", "Cloque",
			"Cloques", "Cobza", "Cobzas", "Concertina", "Concertinas", "Conga", "Congas", "Conque", "Conques", "Contra",
			"Contralto", "Contraltos", "Contras", "Contrebasse", "Contrebasses", "Contrebasson", "Contrebassons",
			"Coquille", "Coquilles", "Cor", "Corna", "Cornas", "Corne", "Cornemuse", "Cornemuses", "Cornes", "Cornet",
			"Cornets", "Cornons", "Cornu", "Cornus", "Coron", "Corons", "Cors", "Coucou", "Coucous", "Courcaillet",
			"Courcaillets", "Courtaud", "Courtauds", "Crapaud", "Crapauds", "Craquettes", "Crash", "Crashes", "Crashs",
			"Crecelle", "Crecelles", "Crecerelle", "Crecerelles", "Cremone", "Cremones", "Crenelle", "Crenelles",
			"Crible", "Cribles", "Cricri", "Cricris", "Crincrin", "Crincrins", "Criquet", "Criquets", "Cromorne",
			"Cromornes", "Crotale", "Crotales", "Cuilleres", "Cuillers", "Cura", "Curas", "Cymbale", "Cymbales",
			"Cymbalum", "Cymbalums", "Czimbalum", "Czimbalums", "Dan", "Dandin", "Dandins", "Dans", "Darbouka",
			"Darboukas", "Defi", "Defis", "Demoiselle", "Demoiselles", "Derbouka", "Derboukas", "Dessus", "Dhole",
			"Dholes", "Diable", "Diables", "Diablotin", "Diablotins", "Diapason", "Diapasons", "Diaule", "Diaules",
			"Didjeridoo", "Didjeridoos", "Dis", "Discorde", "Discordes", "Divan", "Divans", "Djembe", "Djembes", "Do",
			"Dodo", "Dodos", "Dol", "Dole", "Doles", "Dols", "Dondaine", "Dondaines", "Dos", "Doucine", "Doucines",
			"Douzaine", "Douzaines", "Drums", "Duplex", "Echelette", "Echelettes", "Echelle", "Echelles", "Echiquier",
			"Echiquiers", "Elephantine", "Elephantines", "Elyme", "Elymes", "Enclume", "Enclumes", "Epigone",
			"Epigones", "Epinette", "Epinettes", "Esquille", "Esquilles", "Estive", "Estives", "Eunuque", "Eunuques",
			"Ewe", "Ewes", "Exilant", "Exilent", "Fagot", "Fagots", "Fifre", "Fifres", "File", "Files", "Fistule",
			"Fistules", "Flagellum", "Flagellums", "Flageolet", "Flageolets", "Fluta", "Flutas", "Flute", "Fluteau",
			"Fluteaux", "Flutes", "Flutiau", "Flutiaux", "Fol", "Forte", "Fouet", "Fouets", "Foula", "Foulas", "Foule",
			"Foules", "Gadje", "Galoubet", "Galoubets", "Gambe", "Gambes", "Gamelan", "Gamelans", "Gan", "Ganga",
			"Gangas", "Gans", "Gara", "Garas", "Gardon", "Gardons", "Gazou", "Gazous", "Gigue", "Gigues", "Gita",
			"Gitas", "Glas", "Glockenspiel", "Glockenspiels", "Goge", "Goges", "Gomme", "Gommes", "Gonfle", "Gonfles",
			"Gong", "Gongs", "Goura", "Gouras", "Graille", "Grailles", "Gratouille", "Gratouilles", "Grele", "Greles",
			"Grelot", "Grelots", "Grenouille", "Grenouilles", "Grille", "Grilles", "Gronde", "Grondes", "Guette",
			"Guettes", "Guimbarde", "Guimbardes", "Guindai", "Guindais", "Guitare", "Guitares", "Guzla", "Guzlas",
			"Harmonica", "Harmonicas", "Harmonicorde", "Harmonicordes", "Harmonie", "Harmonies", "Harmonieux",
			"Harmonium", "Harmoniums", "Harpa", "Harpas", "Harpe", "Harpes", "Hautbois", "Helicon", "Helicons",
			"Heptacorde", "Heptacordes", "Herpe", "Herpes", "Hexacorde", "Hexacordes", "Hochet", "Hochets", "Hosanna",
			"Hosannas", "Huchet", "Huchets", "Hun", "Huns", "Hydraule", "Hydraules", "Hydraulique", "Hydrauliques",
			"Hydrophone", "Hydrophones", "Jas", "Jazz", "Jura", "Juras", "Ka", "Kas", "Khol", "Khols", "Kit", "Kits",
			"Klaxon", "Klaxons", "Koan", "Koans", "Kombu", "Kombus", "Kora", "Koras", "Koto", "Kotos", "Lamellophone",
			"Lamellophones", "Lapa", "Lapas", "Larigot", "Larigots", "Larynx", "Leu", "Leus", "Libellions", "Liera",
			"Lieras", "Limonaire", "Limonaires", "Linga", "Lingas", "Lira", "Liras", "Lire", "Lires", "Lise", "Lises",
			"Lituus", "Lote", "Lotes", "Lotos", "Lourd", "Lourds", "Loure", "Loures", "Lu", "Lue", "Lues", "Luit",
			"Lus", "Luta", "Lutas", "Luth", "Luths", "Lutina", "Lutinas", "Lyra", "Lyras", "Lyrasse", "Lyrasses",
			"Lyre", "Lyres", "Ma", "Machette", "Machettes", "Macho", "Machos", "Maestro", "Maestros", "Malta", "Maltas",
			"Mandille", "Mandilles", "Mandole", "Mandoles", "Mandoline", "Mandolines", "Mandore", "Mandores",
			"Manichordion", "Manichordions", "Manicorde", "Manicordes", "Manivelle", "Manivelles", "Maraca", "Maracas",
			"Margoulette", "Margoulettes", "Marimba", "Marimbas", "Marionnette", "Marionnettes", "Martelet",
			"Martelets", "Mas", "Mat", "Matou", "Matous", "Mats", "Megaphone", "Megaphones", "Melodica", "Melodicas",
			"Mescal", "Mescals", "Metallophone", "Metallophones", "Mezoued", "Mezoueds", "Mir", "Mirliton", "Mirlitons",
			"Mirs", "Monel", "Monels", "Monocorde", "Monocordes", "Moque", "Moques", "Mouche", "Mouches", "Moulinets",
			"Muse", "Musele", "Museles", "Muses", "Musette", "Musettes", "Nabla", "Nablas", "Nable", "Nables", "Nacre",
			"Nacres", "Nais", "Nasard", "Nasards", "Nay", "Nays", "Ney", "Neys", "Oc", "Ocarina", "Ocarinas", "Octave",
			"Octaves", "Octavin", "Octavins", "Ogre", "Ogres", "Olifant", "Olifants", "Oliphant", "Oliphants",
			"Ophicleide", "Ophicleides", "Orchestrions", "Organe", "Organes", "Orgue", "Orgues", "Orpheon", "Orpheons",
			"Os", "Ou", "Oud", "Ouds", "Palets", "Pan", "Pandore", "Pandores", "Pans", "Panse", "Panses", "Pantalon",
			"Pantalons", "Pardessus", "Patas", "Patouille", "Patouilles", "Pava", "Pavas", "Pentacorde", "Pentacordes",
			"Phenicien", "Pheniciens", "Phenix", "Phoenix", "Pi", "Piano", "Pianoforte", "Pianofortes", "Pianola",
			"Pianolas", "Pianos", "Pibrock", "Pibrocks", "Piccolo", "Piccolos", "Picolo", "Picolos", "Pignates",
			"Pilai", "Pilais", "Pilon", "Pilons", "Pinot", "Pinots", "Pionne", "Pionnes", "Pipa", "Pipas", "Pipe",
			"Pipeau", "Pipeaux", "Pipes", "Pipette", "Pipettes", "Piqueur", "Piqueurs", "Pis", "Piston", "Pistons",
			"Planchettes", "Plaquettes", "Poche", "Poches", "Pochette", "Pochettes", "Polka", "Polkas", "Pommer",
			"Portatif", "Portatifs", "Positif", "Positifs", "Potee", "Potees", "Practice", "Practices", "Protee",
			"Protees", "Psalterion", "Psalterions", "Psautier", "Psautiers", "Pu", "Pus", "Pythique", "Pythiques",
			"Qanun", "Qanuns", "Qin", "Qins", "Quinte", "Quintes", "Quinto", "Rab", "Rabab", "Rababs", "Rabs", "Rachat",
			"Rachats", "Rack", "Racket", "Rackets", "Racks", "Racle", "Racles", "Racleur", "Racleurs", "Racloir",
			"Racloirs", "Raine", "Raines", "Rainette", "Rainettes", "Rale", "Rales", "Rapai", "Rapais", "Rape", "Rapes",
			"Raquette", "Raquettes", "Rebab", "Rebabs", "Rebec", "Rebecs", "Rebelle", "Rebelles", "Rebute", "Rebutes",
			"Reclame", "Reclames", "Recorder", "Regale", "Regales", "Relia", "Relias", "Repiques", "Rhombe", "Rhombes",
			"Ride", "Rides", "Roseau", "Roseaux", "Rosse", "Rosses", "Rossignol", "Rossignols", "Rota", "Rotas", "Rote",
			"Rotes", "Rouler", "Rouleur", "Rouleurs", "Route", "Routes", "Sa", "Sabar", "Sabars", "Sabot", "Sabots",
			"Sacquebute", "Sacquebutes", "Sacra", "Sacras", "Sain", "Sains", "Saint", "Sainte", "Saintes", "Saints",
			"Sambuca", "Sambucas", "Sambuque", "Sambuques", "Sampler", "Samplers", "Sandale", "Sandales", "Sang",
			"Sangs", "Sanza", "Sanzas", "Saqueboute", "Saqueboutes", "Saquebute", "Saquebutes", "Sarangi", "Sarangis",
			"Sarod", "Sarode", "Sarodes", "Sarods", "Saron", "Sarong", "Sarongs", "Sarons", "Sarrussophone",
			"Sarrussophones", "Sas", "Sati", "Satis", "Sautelles", "Sauterie", "Sauteries", "Sautier", "Sautiers",
			"Saxhorn", "Saxhorns", "Saxophone", "Saxophones", "Schofar", "Schofars", "Scraper", "Scrapers", "Se",
			"Second", "Seconds", "Sehtar", "Sehtars", "Sein", "Seing", "Seings", "Seins", "Seraphin", "Seraphine",
			"Seraphines", "Seraphins", "Serinette", "Serinettes", "Serpent", "Serpenteau", "Serpenteaux", "Serpents",
			"Ses", "Setar", "Setars", "Shahnai", "Shahnais", "Shaker", "Shakers", "Shamisen", "Shamisens", "Shana",
			"Shanas", "Si", "Sifflet", "Sifflets", "Sifflote", "Sifflotes", "Sirene", "Sirenes", "Sis", "Sistre",
			"Sistres", "Sitar", "Sitars", "Song", "Songs", "Sonnailles", "Sonnante", "Sonnantes", "Sonnerie",
			"Sonneries", "Sonnette", "Sonnettes", "Souffle", "Souffles", "Soula", "Soulas", "Soum", "Soums", "Sourdine",
			"Sourdines", "Spadice", "Spadices", "Sphere", "Spheres", "Splash", "Spondaique", "Spondaiques", "Squille",
			"Squilles", "Stick", "Sticks", "Stradivarius", "Surdos", "Symphonie", "Symphonies", "Synthetiseur",
			"Synthetiseurs", "Syringe", "Syringes", "Syrinx", "Tabla", "Tablas", "Table", "Tables", "Tablette",
			"Tablettes", "Tabor", "Tabors", "Tabouret", "Tabourets", "Taille", "Tailles", "Tambour", "Tambourin",
			"Tambourine", "Tambourines", "Tambourins", "Tambours", "Tampon", "Tampons", "Tao", "Taos", "Tapette",
			"Tapettes", "Tapon", "Tapons", "Tar", "Tara", "Taras", "Tare", "Tares", "Tari", "Taris", "Tarot", "Tarots",
			"Tars", "Tas", "Tassa", "Tassas", "Tchao", "Tchatcha", "Tchatchas", "Teke", "Tekes", "Tentant", "Tentants",
			"Teorbe", "Teorbes", "Tetracorde", "Tetracordes", "Theorbe", "Theorbes", "Thiol", "Thiols", "Thon", "Thons",
			"Tibia", "Tibias", "Timbale", "Timbales", "Timbre", "Timbres", "Tintinnabule", "Tintinnabules", "Tocsin",
			"Tocsins", "Tom", "Tome", "Tomes", "Toms", "Ton", "Tong", "Tongs", "Tonnant", "Tonnantes", "Tonnants",
			"Tons", "Top", "Tops", "Toquet", "Toquets", "Torree", "Torrees", "Toupin", "Toupins", "Tourterelle",
			"Tourterelles", "Transpositeur", "Transpositeurs", "Traquenard", "Traquenards", "Traquet", "Traquets",
			"Traversiere", "Traversieres", "Trepied", "Trepieds", "Tres", "Tri", "Triangle", "Triangles", "Trictrac",
			"Trictracs", "Trident", "Tridents", "Trigone", "Trigones", "Triple", "Triples", "Tripode", "Tripodes",
			"Tripot", "Tripots", "Tris", "Triton", "Tritons", "Trombe", "Trombes", "Trombone", "Trombones", "Trompe",
			"Trompes", "Trompette", "Trompettes", "Tuba", "Tubas", "Tube", "Tubes", "Tumba", "Tumbas", "Turbe",
			"Turbes", "Turcophone", "Turcophones", "Turelure", "Turelures", "Turlurette", "Turlurettes", "Turlutaine",
			"Turlutaines", "Turlututu", "Tutes", "Tympan", "Tympanon", "Tympanons", "Tympans", "Ukulele", "Ukuleles",
			"Us", "Vaccine", "Vaccines", "Valga", "Valiha", "Valihas", "Venu", "Venus", "Vermillon", "Vermillons",
			"Vesse", "Vesses", "Vessie", "Vessies", "Vibraphone", "Vibraphones", "Vieille", "Vieilles", "Viele",
			"Vieles", "Vielle", "Vielles", "Vigneron", "Vignerons", "Vina", "Vinas", "Viola", "Violas", "Viole",
			"Violes", "Violet", "Violets", "Violette", "Violettes", "Violon", "Violonasse", "Violonasses",
			"Violoncelle", "Violoncelles", "Violone", "Violones", "Violons", "Viorne", "Viornes", "Virginal",
			"Virginale", "Virginales", "Virginals", "Voleur", "Voleurs", "Weber", "Webers", "Xalam", "Xalams",
			"Xylophone", "Xylophones", "Yang", "Yangs", "Yin", "Yins", "Zarb", "Zarbs", "Zingue", "Zingues", "Zourna",
			"Zournas");

	public static ObservableList<String> spe_membre = FXCollections.observableArrayList("Pas de spécialité", "Choriste",
			"Soliste", "Musicien", "Chanteur");

	public static ObservableList<String> respon_membre = FXCollections.observableArrayList("Pas de responsabilité",
			"Chauffeur", "Habilleur", "dirigeant", "trésorier");
}
